export const anime = [
  { 'id': 1, 'title': 'Action', 'img': require('~/assets/images/anime-action.jpg') },
  { 'id': 2, 'title': 'Adventure', 'img': 'https://cdn.myanimelist.net/images/anime/13/17405.jpg' },
  { 'id': 3, 'title': 'Cars', 'img': 'https://cdn.myanimelist.net/images/anime/1404/101364.jpg' },
  { 'id': 4, 'title': 'Comedy', 'img': 'https://cdn.myanimelist.net/images/anime/12/76049.jpg' },
  { 'id': 5, 'title': 'Dementia', 'img': 'https://cdn.myanimelist.net/images/anime/7/77356.jpg' },
  { 'id': 6, 'title': 'Demons', 'img': 'https://cdn.myanimelist.net/images/anime/1286/99889.jpg' },
  { 'id': 7, 'title': 'Mystery', 'img': 'https://cdn.myanimelist.net/images/anime/3/86578.jpg' },
  { 'id': 8, 'title': 'Drama', 'img': 'https://cdn.myanimelist.net/images/anime/7/20310.jpg' },
  { 'id': 9, 'title': 'Ecchi', 'img': require('~/assets/images/anime-ecchi.jpg') },
  { 'id': 10, 'title': 'Fantasy', 'img': '' },
  { 'id': 11, 'title': 'Game', 'img': '' },
  { 'id': 12, 'title': 'Hentai', 'img': '' },
  { 'id': 13, 'title': 'Historical', 'img': '' },
  { 'id': 14, 'title': 'Horror', 'img': '' },
  { 'id': 15, 'title': 'Kids', 'img': '' },
  { 'id': 16, 'title': 'Magic', 'img': '' },
  { 'id': 17, 'title': 'Martial Arts', 'img': '' },
  { 'id': 18, 'title': 'Mecha', 'img': '' },
  { 'id': 19, 'title': 'Music', 'img': '' },
  { 'id': 20, 'title': 'Parody', 'img': '' },
  { 'id': 21, 'title': 'Samurai', 'img': '' },
  { 'id': 22, 'title': 'Romance', 'img': '' },
  { 'id': 23, 'title': 'School', 'img': '' },
  { 'id': 24, 'title': 'Sci-Fi', 'img': '' },
  { 'id': 25, 'title': 'Shoujo', 'img': '' },
  { 'id': 26, 'title': 'Shoujo Ai', 'img': '' },
  { 'id': 27, 'title': 'Shounen', 'img': '' },
  { 'id': 28, 'title': 'Shounen Ai', 'img': '' },
  { 'id': 29, 'title': 'Space', 'img': '' },
  { 'id': 30, 'title': 'Sports', 'img': '' },
  { 'id': 31, 'title': 'Super Power', 'img': '' },
  { 'id': 32, 'title': 'Vampire', 'img': '' },
  { 'id': 33, 'title': 'Yaoi', 'img': '' },
  { 'id': 34, 'title': 'Yuri', 'img': '' },
  { 'id': 35, 'title': 'Harem', 'img': '' },
  { 'id': 36, 'title': 'Slice of Life', 'img': '' },
  { 'id': 37, 'title': 'Supernatural', 'img': '' },
  { 'id': 38, 'title': 'Military', 'img': '' },
  { 'id': 39, 'title': 'Police', 'img': '' },
  { 'id': 40, 'title': 'Psychological', 'img': '' },
  { 'id': 41, 'title': 'Thriller', 'img': '' },
  { 'id': 42, 'title': 'Seinen', 'img': '' },
  { 'id': 43, 'title': 'Josei', 'img': '' }
]

export const manga = [
  { 'id': 1, 'title': 'Action', 'img': '' },
  { 'id': 2, 'title': 'Adventure', 'img': '' },
  { 'id': 3, 'title': 'Cars', 'img': '' },
  { 'id': 4, 'title': 'Comedy', 'img': '' },
  { 'id': 5, 'title': 'Dementia', 'img': '' },
  { 'id': 6, 'title': 'Demons', 'img': require('~/assets/images/manga-demons.jpg') },
  { 'id': 7, 'title': 'Mystery', 'img': '' },
  { 'id': 8, 'title': 'Drama', 'img': require('~/assets/images/manga-drama.jpg') },
  { 'id': 9, 'title': 'Ecchi', 'img': require('~/assets/images/manga-ecchi.jpg') },
  { 'id': 10, 'title': 'Fantasy', 'img': '' },
  { 'id': 11, 'title': 'Game', 'img': '' },
  { 'id': 12, 'title': 'Hentai', 'img': '' },
  { 'id': 13, 'title': 'Historical', 'img': '' },
  { 'id': 14, 'title': 'Horror', 'img': '' },
  { 'id': 15, 'title': 'Kids', 'img': '' },
  { 'id': 16, 'title': 'Magic', 'img': '' },
  { 'id': 17, 'title': 'Martial Arts', 'img': '' },
  { 'id': 18, 'title': 'Mecha', 'img': '' },
  { 'id': 19, 'title': 'Music', 'img': '' },
  { 'id': 20, 'title': 'Parody', 'img': '' },
  { 'id': 21, 'title': 'Samurai', 'img': '' },
  { 'id': 22, 'title': 'Romance', 'img': '' },
  { 'id': 23, 'title': 'School', 'img': '' },
  { 'id': 24, 'title': 'Sci-Fi', 'img': '' },
  { 'id': 25, 'title': 'Shoujo', 'img': '' },
  { 'id': 26, 'title': 'Shoujo Ai', 'img': '' },
  { 'id': 27, 'title': 'Shounen', 'img': '' },
  { 'id': 28, 'title': 'Shounen Ai', 'img': '' },
  { 'id': 29, 'title': 'Space', 'img': '' },
  { 'id': 30, 'title': 'Sports', 'img': '' },
  { 'id': 31, 'title': 'Super Power', 'img': '' },
  { 'id': 32, 'title': 'Vampire', 'img': '' },
  { 'id': 33, 'title': 'Yaoi', 'img': '' },
  { 'id': 34, 'title': 'Yuri', 'img': '' },
  { 'id': 35, 'title': 'Harem', 'img': '' },
  { 'id': 36, 'title': 'Slice of Life', 'img': '' },
  { 'id': 37, 'title': 'Supernatural', 'img': '' },
  { 'id': 38, 'title': 'Military', 'img': '' },
  { 'id': 39, 'title': 'Police', 'img': '' },
  { 'id': 40, 'title': 'Psychological', 'img': '' },
  { 'id': 41, 'title': 'Thriller', 'img': '' },
  { 'id': 42, 'title': 'Seinen', 'img': '' },
  { 'id': 43, 'title': 'Josei', 'img': '' }
]